### ISSUE TITLE
jaxDecomp not compatible with jax 0.4.33

### ISSUE THREAD

**Issue by EiffL** [DifferentiableUniverseInitiative/jaxDecomp#50]
Here is how to reproduce the problem:

https://colab.research.google.com/drive/1mpsrdsAmAqlXawGBCumkz9yoF9gyWmyV?usp=sharing

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-2-c75e24cf9ed3>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import jaxdecomp

3 frames
[/usr/local/lib/python3.10/dist-packages/jax/_src/deprecations.py](https://localhost:8080/#) in getattr(name)
     53       warnings.warn(message, DeprecationWarning, stacklevel=2)
     54       return fn
---> 55     raise AttributeError(f"module {module!r} has no attribute {name!r}")
     56 
     57   return getattr

AttributeError: module 'jax.lax' has no attribute 'FftType'

**Comment by EiffL** [comment]
Which also breaks jaxpm :-(

**Comment by ASKabalan** [comment]
Oh 🥺.

I will take care of this today

**Comment by EiffL** [comment]
Looks like the current version of jax on colab is too old, this seems to work with latest. So I guess maybe it's a matter of imposing a more recent minimum version of jax. But that always causes issues because people then need to know how to install the correct jax variant (cpu or gpu) for their system.

Maybe there is a way to not depend on lax.ffttyp?

**Comment by EiffL** [comment]
Ok, so Ffftype is public since v0.4.35 of JAX. I don't know how the current tests can work with v0.4.30. 

My recommendation is to either:
  - upgrade the dependency to 0.4.35
or
  - define your own Ffftype in fft_utils and use it throughout so that we can remain compatible with older version of jax.

**Comment by ASKabalan** [comment]
What about conditioning on Jax version
Before 35 we import FftType for xla_client?
After 35 we get it from lax

**Comment by EiffL** [comment]
nah, we are not supposed to use anything from xla_client.
But Ftttype is a very small enum, it would be fine to redefine it locally, and eventually remove it in a few months when we can rely on xla.fftype

I've updated the first demo notebook of jaxpm to use latest jax, so for now at least nothing is breaking for people. I'd say we can simply upgrade the dependemcy to 0.4.35

**Comment by EiffL** [comment]
Thanks Wassim :-)
